language: node_js
sudo: required
addons:
  chrome: stable
node_js:
 - "node"

before_install:
  - npm update npm -g
  - npm install -g galenframework-cli


script: galen test tests/homepage.test.js --htmlreport reports