language: node_js
os: osx
node_js:
 - "node"

before_install:
  - npm update npm -g
  - npm install -g galenframework-cli
  - npm install chrome -g

script: galen test tests/homepage.test.js --htmlreport reports